import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :castmill, CastmillWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  url: [
    host:
      if(System.get_env("CASTMILL_HOST") in [nil, "", false],
        do: "localhost",
        else: System.get_env("CASTMILL_HOST")
      ),
    port:
      String.to_integer(
        if System.get_env("CASTMILL_PORT") in [nil, "", false],
          do: "4000",
          else: System.get_env("CASTMILL_PORT")
      )
  ],
  server: true,
  watchers: []

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Castmill.Finch

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# widgets json files
config :castmill, CastmillWeb.Widgets.WidgetsLoader, json_dir: "/app/widged/dist/widgets"
