# Step 1: Building the frontend
FROM node:20 AS builder

# Set the environment variable
ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL:-'http://localhost:4000/dashboard'}

ARG VITE_DOMAIN
ENV VITE_DOMAIN=${VITE_DOMAIN:-'localhost'}

ARG VITE_ORIGIN
ENV VITE_ORIGIN=${VITE_ORIGIN:-'http://localhost:3000'}

# Copy all
COPY . /app

# Set the working directory
WORKDIR /app

# RUN npm install --global yarn
RUN yarn install

# Run the build script for all workspaces
RUN yarn build:all

# Build Dashboard
RUN cd packages/dashboard && npm run build

# Step 2: Setting up the Nginx server
FROM nginx:stable-alpine

# Copy the built assets from the builder stage to the Nginx serve directory
COPY --from=builder /app/packages/dashboard/dist /usr/share/nginx/html

# Optional: If you are using client-side routing, configure Nginx to redirect all requests to your index.html
RUN echo 'server { listen 3000; location / { root /usr/share/nginx/html; index index.html index.htm; try_files $uri $uri/ /index.html; } }' > /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 3000

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
