/// <reference types="vitest" />
/// <reference types="vite/client" />

import { defineConfig } from 'vite';
import solidPlugin from 'vite-plugin-solid';
import legacy from '@vitejs/plugin-legacy';

export default defineConfig({
  plugins: [
    legacy({
      targets: {
        chrome: '38',
      },
      renderModernChunks: false,
      polyfills: [
        'es/map',
        'es/set',
        'es/promise',
        'web.queue-microtask',
        'es.promise.finally',
        'es.array.at',
        'es.array.concat',
        'es.array.copy-within',
        'es.array.every',
        'es.array.fill',
        'es.array.filter',
        'es.array.find-index',
        'es.array.find-last-index',
        'es.array.find-last',
        'es.array.find',
        'es.array.flat-map',
        'es.array.flat',
        'es.array.for-each',
        'es.array.from',
        'es.array.includes',
        'es.array.index-of',
        'es.array.is-array',
        'es.array.iterator',
        'es.array.join',
        'es.array.last-index-of',
        'es.array.map',
        'es.array.of',
        'es.array.push',
        'es.array.reduce-right',
        'es.array.reduce',
        'es.array.reverse',
        'es.array.slice',
        'es.array.some',
        'es.array.sort',
        'es.array.species',
        'es.array.splice',
        'es.array.to-reversed',
        'es.array.to-sorted',
        'es.array.to-spliced',
        'es.array.unscopables.flat',
        'es.array.unscopables.flat-map',
        'es.array.unshift',
        'es.array.with',
        'es.object.assign',
        'es.object.create',
        'es.object.define-getter',
        'es.object.define-properties',
        'es.object.define-property',
        'es.object.define-setter',
        'es.object.entries',
        'es.object.freeze',
        'es.object.from-entries',
        'es.object.get-own-property-descriptor',
        'es.object.get-own-property-descriptors',
        'es.object.get-own-property-names',
        'es.object.get-own-property-symbols',
        'es.object.get-prototype-of',
        'es.object.group-by',
        'es.object.has-own',
        'es.object.is-extensible',
        'es.object.is-frozen',
        'es.object.is-sealed',
        'es.object.is',
        'es.object.keys',
        'es.object.lookup-getter',
        'es.object.lookup-setter',
        'es.object.prevent-extensions',
        'es.object.proto',
        'es.object.seal',
        'es.object.set-prototype-of',
        'es.object.to-string',
        'es.object.values',
        'es.string.anchor',
        'es.string.at-alternative',
        'es.string.big',
        'es.string.blink',
        'es.string.bold',
        'es.string.code-point-at',
        'es.string.ends-with',
        'es.string.fixed',
        'es.string.fontcolor',
        'es.string.fontsize',
        'es.string.from-code-point',
        'es.string.includes',
        'es.string.is-well-formed',
        'es.string.italics',
        'es.string.iterator',
        'es.string.link',
        'es.string.match-all',
        'es.string.match',
        'es.string.pad-end',
        'es.string.pad-start',
        'es.string.raw',
        'es.string.repeat',
        'es.string.replace-all',
        'es.string.replace',
        'es.string.search',
        'es.string.small',
        'es.string.split',
        'es.string.starts-with',
        'es.string.strike',
        'es.string.sub',
        'es.string.substr',
        'es.string.sup',
        'es.string.to-well-formed',
        'es.string.trim-end',
        'es.string.trim-left',
        'es.string.trim-right',
        'es.string.trim-start',
        'es.string.trim',
      ],
    }),
    /* 
    Uncomment the following line to enable solid-devtools.
    For more info see https://github.com/thetarnav/solid-devtools/tree/main/packages/extension#readme
    */
    // devtools(),
    solidPlugin(),
  ],
  base: '',
  publicDir: 'public',
  server: {
    host: '0.0.0.0',
    port: 3003,
  },
  preview: {
    host: '0.0.0.0',
    port: 3003,
  },
  test: {
    environment: 'jsdom',
    globals: true,
    // setupFiles: ['node_modules/@testing-library/jest-dom/vitest'],
    // if you have few tests, try commenting this
    // out to improve performance:
    isolate: false,
  },
  build: {
    minify: false,
    sourcemap: 'inline',
  },
  resolve: {
    conditions: ['development', 'browser'],
  },
});
