export enum Action {
  RELAUNCH = 'RELAUNCH',
  QUIT = 'QUIT',
  SHUTDOWN = 'SHUTDOWN',
  REBOOT = 'REBOOT',
  UPDATE = 'UPDATE',
  // UPDATE_FIRMWARE = 'UPDATE_FIRMWARE',
  GET_MACHINE_GUID = 'GET_MACHINE_GUID',
}
