export enum Action {
  RELAUNCH = 'RELAUNCH',
  QUIT = 'QUIT',
  SHUTDOWN = 'SHUTDOWN',
  REBOOT = 'REBOOT',
  UPDATE = 'UPDATE',
  // UPDATE_FIRMWARE = 'UPDATE_FIRMWARE',
  GET_MACHINE_GUID = 'GET_MACHINE_GUID',
  GET_STORE_VALUE = 'GET_STORE_VALUE',
  SET_STORE_VALUE = 'SET_STORE_VALUE',
  DELETE_STORE_VALUE = 'DELETE_STORE_VALUE',

  GET_LOCATION = 'GET_LOCATION',

  // File system
  FS_INIT = 'FS_INIT',
  FS_INFO = 'FS_INFO',
  FS_LIST_FILES = 'FS_LIST_FILES',
  FS_STORE_FILE = 'FS_STORE_FILE',
  FS_RETRIEVE_FILE = 'FS_RETRIEVE_FILE',
  FS_DELETE_FILE = 'FS_DELETE_FILE',
  FS_DELETE_ALL_FILES = 'FS_DELETE_ALL_FILES',
}
